containers fixes

diff --git a/CONTAINERS/SubmitWorkStream b/CONTAINERS/SubmitWorkStream
--- a/CONTAINERS/SubmitWorkStream
+++ b/CONTAINERS/SubmitWorkStream
@@ -1,36 +1,48 @@
 #!/bin/bash
+usage() {
+cat <<EOT
+  usage: ${0##*/} -wall n_seconds -cpus n_cpus -nodesize n_cores -queue q_name -name job_name [-submit] -cfg config_file
+EOT
+exit 0
+}
+[[ "$1" == -h || "$1" == --help ]] && usage
 #===============================================================================
 #                    start of section to be adjusted by user                   #
 #===============================================================================
-walltime=600             # wall clock time for container
-cpus=16                  # number of cores needed by container
-QuEuE=""                 # queue to submit to
-name="InputAndModel"     # job name for container
+#
+# example using 24 cores (2 nodes with 12 cores each)
+#
+wall=600             # wall clock time for container
+cpus=24                  # number of cores needed by container
+nodesize=12
+queue="12"                 # queue to submit to
+name="AtmOceCoupled"     # job name for container
+submit=""
+cfg=""
 #===============================================================================
 #                     end of section to be adjusted by user                    #
 #===============================================================================
+#
+[[ -n ${queue} ]] && queue="-q ${queue}"
 #
 unset QUEUE_1CPU
 unset QUEUE_2CPU
 unset QUEUE_3CPU
 unset QUEUE_4CPU
 #
-# example using 8 cores (1 node with 8 cores each)
-# 4  1 way queues (2 threads per process)
+ContainerJob=${TMPDIR}/ContainerJob_$$
+VERSION=1.0
+which run_work_stream_${VERSION} >/dev/null   || { echo "ERROR: run_work_stream_${VERSION} not found, ABORTING" 1>&2; exit 1 ; }
+which pick_and_run_work_${VERSION} >/dev/null || { echo "ERROR: pick_and_run_work_${VERSION} not found, ABORTING"  1>&2; exit 1 ; }
 #
-export ContainerJob=${TMPDIR}/ContainerJob_$$
-export VERSION=1.0
-echo "export RunWorkStream=$(which run_work_stream_${VERSION})" >${ContainerJob}
-echo "export PickAndRunWork=$(which pick_and_run_work_${VERSION})" >>${ContainerJob}
+cat <<EOJ >${ContainerJob}
+export RunWorkStream="$(which run_work_stream_${VERSION})"
+export PickAndRunWork="$(which pick_and_run_work_${VERSION})"
+wall=${wall}
+nodesize=${nodesize}
+EOJ
+#
 cat <<\EOJ >>${ContainerJob}
-#===============================================================================
-#                    start of section to be adjusted by user                   #
-#===============================================================================
-walltime=600   # repeated because there is no substitution in "here document"
-nodesize=8
-#===============================================================================
-#                     end of section to be adjusted by user                    #
-#===============================================================================
 #
 # get list of processes for which a taskset will have to be applied
 #
@@ -113,28 +125,17 @@ export NODEFILE_PBS=${NodeFileDir}/nodes.master
 export FORCE_SETUP=yes
 export name=""
 export queues=""
-#===============================================================================
-#                    start of section to be adjusted by user                   #
-#===============================================================================
-#
-#------------------------------------------------------------------------------------------------------------------------------
-# launch 1 x 12 way queue, 1 thread per process
-#------------------------------------------------------------------------------------------------------------------------------
-export maxidle=60
-name=micro12 ; queues="${name}" ; BATCH_MPI_CPUS=12 ; export OMP_NUM_THREADS=1 ;   # 12 processes with 1 thread  = 12 cores
-instanciate 0:4-7 1:0-7      # node 0 cpus 4-7, node 1 cpus 0-7
-#------------------------------------------------------------------------------------------------------------------------------
-# launch 2 x 1 way queues
-#------------------------------------------------------------------------------------------------------------------------------
-#export maxidle=${walltime}
-export maxidle=60
-name=micro1 ; queues="${name} ${name}-1" ; BATCH_MPI_CPUS=1 ; export OMP_NUM_THREADS=2         # 2 cores per instance = 2 cores
-instanciate 0:0-1           # node 0, cpu 0-1
-name=micro2 ; queues="${name} ${name}-1" ; BATCH_MPI_CPUS=1 ; export OMP_NUM_THREADS=2         # 2 cores per instance = 2 cores
-instanciate 0:2-3           # node 0, cpu 2-3
-#===============================================================================
-#                     end of section to be adjusted by user                    #
-#===============================================================================
+EOJ
+[[ -z ${cfg} ]] && cfg=${0%/*}/demo_container.cfg && submit="" && echo "INFO: demo mode" 1>&2
+echo "INFO: using configuration file '${cfg}'" 1>&2
+if [[ -r ${cfg} ]] ; then          # user supplied or demo config file
+  cat ${cfg} >>${ContainerJob}
+else
+  echo "ERROR: no config file specified, ABORTING" 1>&2
+  rm -f ${ContainerJob}
+  exit 1
+fi
+cat <<\EOJ >>${ContainerJob}
 #------------------------------------------------------------------------------------------------------------------------------
 wait   # wait for backgrounded sub-containers to terminate
 #------------------------------------------------------------------------------------------------------------------------------
@@ -142,7 +143,10 @@ rm -f ${InstanceQuitFile}  # global quit signal file
 rm -f ${NodeFileDir}/*     # remove node files
 rmdir ${NodeFileDir}       # directory should now be empty, remove it
 EOJ
-cat ${ContainerJob}
-echo "ord_soumet ${ContainerJob} -t ${walltime} -mpi -cpus ${cpus}x1 -jn ${name} -shell nologin ${QuEuE} $@"
-#ord_soumet ${ContainerJob} -t ${walltime} -mpi -cpus ${cpus}x1 -jn ${name} -shell nologin ${QuEuE} "$@"
+printf "\n\nord_soumet ${ContainerJob} -t ${wall} -mpi -cpus ${cpus}x1 -jn ${name} -shell nologin ${queue} $@\n\n\n" 1>&2
+if [[ -n $submit ]] ; then
+  ord_soumet ${ContainerJob} -t ${wall} -mpi -cpus ${cpus}x1 -jn ${name} -shell nologin ${queue} "$@"
+else
+  cat ${ContainerJob}
+fi
 rm -f ${ContainerJob}
